services:
  squid-proxy:
    image: ubuntu/squid
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid-cache/squid.conf:/etc/squid/squid.conf
      - ./squid-cache/domain_blacklist.txt:/etc/squid/domain_blacklist.txt
      - ./squid-cache/keyword_blacklist.txt:/etc/squid/keyword_blacklist.txt
      - /srv/docker/squid/cache:/var/spool/squid
    restart: always

  apache:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    image: ubuntu/apache2
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./apache2/sites:/var/www
      - ./apache2/sites-available:/etc/apache2/sites-available

  bind:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/zones/db.prored.test:/etc/bind/zones/db.prored.local
    restart: always
