services:
  squid-proxy:
    image: ubuntu/squid
    container_name: squid
    networks:
      prored_test:
        ipv4_address: 192.168.100.3
    ports:
      - "3128:3128"
    volumes:
      - ./squid-cache/squid.conf:/etc/squid/squid.conf
      - ./squid-cache/domain_blacklist.txt:/etc/squid/domain_blacklist.txt
      - ./squid-cache/keyword_blacklist.txt:/etc/squid/keyword_blacklist.txt
      - /srv/docker/squid/cache:/var/spool/squid
    restart: always

  apache:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    container_name: apache
    networks:
      prored_test:
        ipv4_address: 192.168.100.4
    ports:
      - "80:80"

  bind:
    image: ubuntu/bind9
    container_name: bind
    networks:
      prored_test:
        ipv4_address: 192.168.100.2
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/zones/db.prored.test:/etc/bind/zones/db.prored.test
    restart: always

networks:
  prored_test:
    external: true
    name: prored_test
