services:
  squid-proxy:
    image: ubuntu/squid
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid-cache/squid.conf:/etc/squid/squid.conf
      - ./squid-cache/domain_blacklist.txt:/etc/squid/domain_blacklist.txt
      - ./squid-cache/keyword_blacklist.txt:/etc/squid/keyword_blacklist.txt
      - /srv/docker/squid/cache:/var/spool/squid
    networks:
      prored:
        ipv4_address: 172.24.0.2
    restart: always

  apache:
    image: ubuntu/apache2
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./apache2/sites:/var/www
      - ./apache2/sites-available:/etc/apache2/sites-available
    networks:
      prored:
        ipv4_address: 172.24.0.4

  bind:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind9/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/zones/db.prored.local:/etc/bind/zones/db.prored.local
      - ./bind9/zones/db.172.24:/etc/bind/zones/db.172.24
    networks:
      prored:
        ipv4_address: 172.24.0.3
    restart: always

networks:
  prored:
    external: true
    name: prored
