services:
  squid-cache:
    build:
      context: ./squid-cache
      dockerfile: Dockerfile
    container_name: squid
    networks:
      prored_test:
        ipv4_address: 172.24.0.3
        mac_address: 02:42:ac:18:00:03
    ports:
      - "3128:3128"
    restart: always

  apache:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    container_name: apache
    networks:
      prored_test:
        ipv4_address: 172.24.0.4
    ports:
      - "80:80"
    restart: always

  bind:
    build:
      context: ./bind9
      dockerfile: Dockerfile
    container_name: bind
    networks:
      prored_test:
        ipv4_address: 172.24.0.2
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always

networks:
  prored_test:
    external: true
    name: prored_test
